"""
Formatter module - formats lesson plans into readable output.
"""

from typing import Dict, Any


def format_markdown(lesson_plan: Dict[str, Any]) -> str:
    """
    Format a lesson plan dictionary as Markdown.

    Args:
        lesson_plan: The lesson plan dictionary.

    Returns:
        Markdown-formatted string.
    """
    lines = []

    lines.append(f"# {lesson_plan['title']}")
    lines.append("")
    lines.append(f"**Duration:** {lesson_plan['duration_minutes']} minutes")
    lines.append("")

    # Learning Objectives
    lines.append("## Learning Objectives")
    lines.append("")
    for obj in lesson_plan["objectives"]:
        lines.append(f"- {obj}")
    lines.append("")

    # Materials
    lines.append("## Materials Needed")
    lines.append("")
    for mat in lesson_plan["materials"]:
        lines.append(f"- {mat}")
    lines.append("")

    # Lesson Structure
    lines.append("## Lesson Structure")
    lines.append("")
    for section in lesson_plan["structure"]:
        lines.append(f"### {section['name']} ({section['duration']} min)")
        lines.append("")
        lines.append(section["description"])
        lines.append("")
        lines.append("_Add specific content, questions, and activities here._")
        lines.append("")

    # Notes
    if lesson_plan.get("notes"):
        lines.append("## Additional Notes")
        lines.append("")
        lines.append(lesson_plan["notes"])
        lines.append("")

    lines.append("---")
    lines.append("*This is a first-draft lesson plan generated by the Lesson Plan Scaffolder.*")

    return "\n".join(lines)


def format_text(lesson_plan: Dict[str, Any]) -> str:
    """
    Format a lesson plan as plain text.

    Args:
        lesson_plan: The lesson plan dictionary.

    Returns:
        Plain text formatted string.
    """
    lines = []

    lines.append(f"LESSON PLAN: {lesson_plan['title']}")
    lines.append(f"Duration: {lesson_plan['duration_minutes']} minutes")
    lines.append("")
    lines.append("LEARNING OBJECTIVES:")
    for obj in lesson_plan["objectives"]:
        lines.append(f"  - {obj}")
    lines.append("")
    lines.append("MATERIALS:")
    for mat in lesson_plan["materials"]:
        lines.append(f"  - {mat}")
    lines.append("")
    lines.append("STRUCTURE:")
    for section in lesson_plan["structure"]:
        lines.append(f"  [{section['duration']} min] {section['name']}")
        lines.append(f"    {section['description']}")
        lines.append("")

    return "\n".join(lines)
